export const icons = {
  arrow_left: require("assets/icon/arrow_left.svg").default,
  message: require("assets/icon/message.svg").default,
  dashboard: require("assets/icon/dashboard.svg").default,
  active_dashboard: require("assets/icon/activeDashboard.svg").default,
  school: require("assets/icon/school.svg").default,
  active_school: require("assets/icon/activeSchool.svg").default,
  subscriptions: require("assets/icon/subscriptions.svg").default,
  active_subscriptions: require("assets/icon/activeSubscriptions.svg").default,
  admin_panel: require("assets/icon/adminPanel.svg").default,
  active_admin_panel: require("assets/icon/activeAdminPanel.svg").default,
  approvals: require("assets/icon/approvals.svg").default,
  active_approvals: require("assets/icon/activeApprovals.svg").default,
  help_request: require("assets/icon/helpRequest.svg").default,
  active_help_request: require("assets/icon/activeHelpRequest.svg").default,
  blog: require("assets/icon/blog.svg").default,
  active_blog: require("assets/icon/activeBlog.svg").default,
  audit_logs: require("assets/icon/auditLogs.svg").default,
  active_audit_logs: require("assets/icon/activeAuditLogs.svg").default,
  settings: require("assets/icon/setting.svg").default,
  active_settings: require("assets/icon/activeSetting.svg").default,
  notification: require("assets/icon/notifications.svg").default,
  refresh_icon: require("assets/icon/refresh.svg").default,
  more: require("assets/icon/more.svg").default,
  angle_down: require("assets/icon/angle_down.svg").default,
  angle_up: require("assets/icon/angle_up.svg").default,
};

export default icons;
