import { RowDataForAuditLog, RowDataForSubscription } from "types";

export const NavConstants = [
  { name: "Subscription" },
  { name: "Date Purchased" },
  { name: "Expiration" },
  { name: "Admin" },
];

export const AuditLog = [{ name: "Date" }, { name: "Time" }, { name: "Role" }];

export const AuditLogData: RowDataForAuditLog[] = [
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
  {
    date_and_time: "9th June, 12:24pm",
    user: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    role: "Sign In Admin",
    action: "Lorem Ipsum",
  },
];

export const subscriptionInitialData: RowDataForSubscription[] = [
  {
    id: "1",
    name: "John Doe",
    imgUrl: "https://i.pravatar.cc/150?img=1",
    purchaseDate: "9th June, 2024",
    amount: "N50,000",
    expiration: "Premium",
    admin: "Samson Edeh",
    subscription: "Premium",
  },
  {
    id: "2",
    name: "Jane Smith",
    imgUrl: "https://i.pravatar.cc/150?img=2",

    subscription: "Standard",
    purchaseDate: "9th June, 2024",
    amount: "N39,500",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
  {
    id: "3",
    name: "Bob Johnson",
    imgUrl: "https://i.pravatar.cc/150?img=3",
    subscription: "Customized",
    purchaseDate: "9th June, 2024",
    amount: "N12,300",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
  {
    id: "4",
    name: "Alice Brown",
    imgUrl: "https://i.pravatar.cc/150?img=4",
    subscription: "Premium",
    purchaseDate: "9th June, 2024",
    amount: "N105,650",
    expiration: "Standard",
    admin: "Samson Edeh",
  },
  {
    id: "5",
    name: "Charlie White",
    imgUrl: "https://i.pravatar.cc/150?img=5",
    subscription: "Standard",
    purchaseDate: "9th June, 2024",
    amount: "N35,000",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
  {
    id: "6",
    name: "Emily Davis",
    imgUrl: "https://i.pravatar.cc/150?img=6",
    subscription: "Customized",
    purchaseDate: "9th June, 2024",
    amount: "",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
  {
    id: "7",
    name: "Michael Wilson",
    imgUrl: "https://i.pravatar.cc/150?img=7",
    subscription: "Premium",
    purchaseDate: "9th June, 2024",
    amount: "",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
  {
    id: "8",
    name: "Sophia Martinez",
    imgUrl: "https://i.pravatar.cc/150?img=8",
    subscription: "Standard",
    purchaseDate: "9th June, 2024",
    amount: "",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
  {
    id: "9",
    name: "James Anderson",
    imgUrl: "https://i.pravatar.cc/150?img=9",
    subscription: "Customized",
    purchaseDate: "9th June, 2024",
    amount: "",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
  {
    id: "10",
    name: "Olivia Thompson",
    imgUrl: "https://i.pravatar.cc/150?img=10",
    subscription: "Premium",
    purchaseDate: "9th June, 2024",
    amount: "",
    expiration: "Premium",
    admin: "Samson Edeh",
  },
];
